apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-reader
  namespace: prod
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: data-reader
        image: aminehajali/pfe-search-engine-datareader
        imagePullPolicy: Always
        env:
        - name: NEO4J_URL
          value: bolt://neo4j:7687
        - name: NEO4J_USERNAME
          value: neo4j
        - name: NEO4J_PASSWORD
          value: pwd
        - name: SIGNOZ_BACKEND
          value: signoz-k8s-infra-otel-agent.monitoring-v2
        - name: SERVICE_NAME
          value: data_reader_dev
