apiVersion: batch/v1
kind: CronJob
metadata:
  name: scrapper
  namespace: prod
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: scrapper
            image: aminehajali/pfe-search-engine-scrapper
