replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: "50"
    memory: "50Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
  
volumeClaimTemplate:
  resources:
    requests:
      storage: 500M