agent:
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
collector:
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
query:
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
cassandra:
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
