datasources:
   -  access: 'proxy'
      editable: true
      is_default: true
      name: 'prom'
      org_id: 1
      type: 'prometheus'
      url: 'http://prometheus-grafana-server'
      version: 1