apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa

bases:
  - ../base

patchesStrategicMerge:
  - patches/cluster.rabbitmqcluster.yml
  - patches/data-loader.deploy.yml
  - patches/data-loader.svc.yml
  - patches/data-reader.deploy.yml
  - patches/data-reader.svc.yml
  - patches/front.deploy.yml
  - patches/front.svc.yml
  - patches/scrapper.cronjob.yml
