apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-reader
  namespace: prod
spec:
  replicas: 1
  template:
    spec:
      initContainers:
      - name: wait-for-neo4j
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup neo4j.dev.svc; do echo 'waiting for neo4j'; sleep 2; done"]

      containers:
      - name: data-reader
        image: aminehajali/pfe-search-engine-datareader
        imagePullPolicy: Always
        env:
        - name: NEO4J_URL
          value: bolt://neo4j.dev.svc:7687
        - name: NEO4J_USERNAME
          value: neo4j
        - name: NEO4J_PASSWORD
          value: pwd
        - name: SIGNOZ_BACKEND
          value: signoz-k8s-infra-otel-agent.monitoring-v2
        - name: SERVICE_NAME
          value: data_reader_qa
        # ports:
        # - containerPort: 5000
