apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: prod
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "*"
spec:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 10Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  rabbitmq:
      additionalConfig: |
        loopback_users = none
        default_user = guest
        default_pass = guest
