apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-reader
  namespace: prod
  labels:
    app: data-reader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-reader
  template:
    metadata:
      labels:
        app: data-reader
    spec:
      initContainers:
      - name: wait-for-neo4j
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup neo4j; do echo 'waiting for neo4j'; sleep 2; done"]

      containers:
      - name: data-reader
        image: aminehajali/pfe-search-engine-datareader
        imagePullPolicy: Always
        env:
        - name: NEO4J_URL
          value: bolt://neo4j:7687
        - name: NEO4J_USERNAME
          value: neo4j
        - name: NEO4J_PASSWORD
          value: pwd
        - name: SIGNOZ_BACKEND
          value: jaeger-k8s-infra-otel-agent.monitoring
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: "3"
            memory: 2Gi
