apiVersion: v1
kind: Service
metadata:
  name: data-loader
  namespace: prod
spec:
  selector:
    app: data-loader
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
