apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader
  namespace: prod
  labels:
    app: data-loader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-loader
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup rabbitmq; do echo 'waiting for rabbitmq'; sleep 2; done"]
      - name: wait-for-neo4j
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup neo4j; do echo 'waiting for neo4j'; sleep 2; done"]

      containers:
      - name: data-loader
        image: aminehajali/pfe-search-engine-dataloader
        env:
        - name: NEO4J_URL
          value: bolt://neo4j:7687
        - name: NEO4J_USERNAME
          value: neo4j
        - name: NEO4J_PASSWORD
          value: pwd
        - name: RABBITMQ_URL
          value: amqp://guest:guest@rabbitmq:5672/
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: "3"
            memory: 2Gi
