apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: prod
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: aminehajali/pfe-search-engine-front
        imagePullPolicy: Always
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://api.pfesearchengine.com
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: "3"
            memory: 2Gi
