apiVersion: batch/v1
kind: CronJob
metadata:
  name: scrapper
  namespace: prod
spec:
  schedule: "	0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          initContainers:
          - name: wait-for-rabbitmq
            image: busybox:1.28
            command: ['sh', '-c', "until nslookup rabbitmq; do echo 'waiting for rabbitmq'; sleep 2; done"]
          containers:
          - name: scrapper
            image: aminehajali/pfe-search-engine-scrapper
            imagePullPolicy: Always
            env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672/
            - name: NB_PAGES_TO_SCRAP
              value: "2"
